[package]
name = "serialization-tests"
version = "0.1.0"
authors = ["bluss"]
publish = false

[lib]
test = false

[dependencies]
ndarray-sgx = { path = "../", features = ["serde-1", "rustc-serialize"] }

[features]
default = ["ron"]

[dev-dependencies.rustc-serialize]
version = "0.3.21"

[dev-dependencies.serde]
version = "1.0"

[dev-dependencies.serde_json]
version = "1.0"

[dev-dependencies.rmp-serde]
version = "0.13.1"

[dependencies.ron]
version = "0.1.1"
optional = true
